### ISSUE TITLE
Need help installing framework on windows

### ISSUE THREAD

**Issue by igrm** [glacejs/glace-js#33]
Hello, 

I cannot execute "glace":
![image](https://user-images.githubusercontent.com/24625265/50576070-8714d380-0e12-11e9-8c3a-983115633a1a.png)

![image](https://user-images.githubusercontent.com/24625265/50576078-a7449280-0e12-11e9-9153-300b622a3dfe.png)

All packages are installed successfuly
![image](https://user-images.githubusercontent.com/24625265/50576087-d1965000-0e12-11e9-9779-4bdeaa24a901.png)

Could you please help me regarding this issue?

Thank you!

**Comment by schipiga** [comment]
hello @igrm , thank you for report. I will glance it this weekend.

**Comment by schipiga** [comment]
hey @igrm, unfortunately I can't reproduce your issue with my Windows 8.1 machine. On my side it was installed and launched well. But I noted 2 diffs between your and mine case:
1. I launched it as a user, not as admin.
2. I don't have explicit path to `glace-js` in `%PATH%` env var. And I also was surprised to see it in your, because `bin/glace` isn't executable file, but just a script, which is launched by `nodejs` via `npm`, as I know. [Here](https://docs.npmjs.com/files/package.json#bin) is more details how it work with `npm`.

Pls, ping me, if you will find a root cause.

**Comment by igrm** [comment]
Thank you for a quick response!

In order to avoid such issues, it would be nice to have step-by-step instruction on how to install glace-js.
Currently, I just don't understand where I am wrong.

**Comment by igrm** [comment]
![image](https://user-images.githubusercontent.com/24625265/50680321-ed1a7a00-100f-11e9-8160-556d21d3b2c4.png)

Now I see stack trace:

Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\igor\Documents\Experiments\GlaceJSTest\node_modules\sharp\lib\constructor.js:10:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\igor\Documents\Experiments\GlaceJSTest\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by schipiga** [comment]
@igrm this issue is related with `sharp` deps: https://github.com/gatsbyjs/gatsby/issues/4693.
I hope the issue last advise should help: try to clear & reinstall `glace-js` from scratch. Also, be sure, that you have installed native dependencies compiler. Or you can install with `npm i -g windows-build-tools`

**Comment by igrm** [comment]
![image](https://user-images.githubusercontent.com/24625265/50681838-8c8e3b80-1015-11e9-95ad-75c1be35514a.png)

I got a message: Cannot read property 'url' of undefined while running the file first-test.js from Quickstart tutorial

**Comment by schipiga** [comment]
@igrm in quickstart tutorial there is cli option `--web`, which activates selenium staff. Try to use it too.

**Comment by igrm** [comment]
![image](https://user-images.githubusercontent.com/24625265/50682315-20143c00-1017-11e9-93c3-fdd6b9260668.png)
Thank you, my friend! Now it runs error-free.

**Comment by schipiga** [comment]
@igrm , you are welcome :) Feel free to ping me, if will have any questions about glacejs. On my side I will actualise readme, to make clear how to install & launch it.
